spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/h2-databases/addressBook;
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

flyway:
  enabled: true